export const projects = [
  {
    title: "Respinos Health",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["React Native", "Firebase", "Express.js", "Openfire", "PostgreSQL"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Humanoid Soccer Robot",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["C++", "ROS", "OpenCV"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Guitar Division Bot",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["Django", "Google Calendar", "PostgreSQL"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Agenda SQL",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["TypeScript", "Sequelize"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Academic Monitoring System",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["Next.js", "Express.js", "PostgreSQL"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Nyampih Branding Web",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["Vue.js", "App Script", "Google Sheet"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Halma AI",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["React"],
    links: [],
    paragraphs: [],
  },
  {
    title: "Spark Data Streaming",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    img: "/landscape_1.jpg",
    techs: ["Apache Spark", "Apache Kafka", "Hadoop", "MySQL"],
    links: [],
    paragraphs: [],
  },
];
